### ISSUE TITLE
Feature Request: Option to require a certain amount of Pin reactions

### ISSUE THREAD

**Issue by boktai1000** [Xwilarg/Pina#1]
I would like to request a feature for the Bot - for the option for a "community based voting" for pinning subjects - say for example I want to require 5 Pin reactions for Pina to pin something in a channel.

Something really basic like this, nothing crazy like per channel settings or anything just a global setting that could be configured and require more than one person reacting in order to pin a topic

Thanks for the great bot!

**Comment by Xwilarg** [comment]
Thanks for the suggestion, I'll work on it and keep you updated touch when it'll be done
Please expect up to one week for the feature to be here

**Comment by Xwilarg** [comment]
The feature is now here, you can enable it by doing
```
@Pina#1027 VoteRequired [number of votes required]
```
I'll then display a vote like that:
![image](https://user-images.githubusercontent.com/20053454/115119738-3bb66d00-9faa-11eb-86df-7a4886819106.png)

Please tell me if everything works fine on your side

**Comment by Xwilarg** [comment]
I'm closing the PR since I have no news on your side, feel free to reopen it if needed
