### ISSUE TITLE
Feature Request: An option for Pina to not give a prompt when a user starts a vote for a message to get pinned.

### ISSUE THREAD

**Issue by xayanide** [Xwilarg/Pina#2]
### My feature request.

An option in the command list so that Pina will not send a prompt whenever a user starts a vote to get a message pinned or unpinned using the 📌 emoji or the 🚫.

Referring to this prompt: 
https://github.com/Xwilarg/Pina/issues/1#issuecomment-821849148

---

### Introduction: Overview on how it currently works on default & with voterequired setting changed.
**Pina bot on default**: 
- Only requires 1 📌 emoji reaction to pin a message in a channel, 
- Does not send a prompt or message & embed when a user reacts to a message with 📌 emoji.

**Pina bot with voterequired setting changed**:
Setting up votesrequired to anything other than 1, for instance:
Pina bot settings:
voterequired = 5

When a user reacts with 📌 on a message: 
Pina bot: 
- Sends a message in that channel about a user that started a pin vote on the message & says that it only requires 4 votes left.

Image example: 
https://github.com/Xwilarg/Pina/issues/1#issuecomment-821849148

Pina bot prompts whenever a user starts a vote on a message because they're requesting to pin it but requires a certain amount of votes for Pina to pin it. 

---

### Why implement this?

A channel gets quickly flooded especially in a public server whenever a user starts a vote to a message with 📌 because Pina bot always prompts whenever a vote is started.

This feature request prevents that from happening.

---

### How will it going to work with this feature?

When a user starts a vote for a message to get pinned using 📌 that requires x number of votes:

Pina bot should:
- Neither prompt nor send or create any new messages about a vote that started.
- Read the message's number of reactions that got voted.
- Wait for the message reach the number of reactions to get pinned. 

When that message reaches the required x number of votes:

Pina should: 
- Pin the message.
- Neither prompt, nor send a message or any embed about the votes.

Pretty simple. 

---

To clarify, Pina bot should:
1. Not give a prompt when a user starts a vote.
2. Continue reading the message's reactions that got voted.
3. Wait for that message to reach x number of reactions.
4. Passively pin the message when a message meets the required number of reactions.

---

### Off-topic
This feature can also be improved by adding a setting that allows a specific channel to get prompts & channels that do not get any prompts, a whitelist/ignorelist for prompts, but this one is out of the main point of this issue.

**Comment by Xwilarg** [comment]
Thanks for your feature request, I'll probably implement this and do a command to enable this behavior
I'll probably start working on it around monday, I'll keep you in touch when it'll be done

**Comment by Xwilarg** [comment]
Hey,
Just letting a small message to you keep in touch, since it's been one week

I've been wanting to rewrote Pina code because it's been a bit messy (and I need to add support for slash commands since it'll be mandatory), I've been planning to add your feature after that

So yeah, just to tell you that I didn't forget you but it will take me a bit more time

**Comment by wertercatt** [comment]
Chiming in to say I would also like this functionality.

**Comment by Xwilarg** [comment]
I totally forgot about this issue, I'm a bit busy these days but I'll try to go back on it before next week

**Comment by Xwilarg** [comment]
This should now be implemented, please tell me if everything work as expected
